In [1]:

import numpy as np

import pynq

ol = pynq.Overlay("/home/xilinx/jupyter_notebooks/workshop/Session_2/pynq_tutorial/hw/bitstream/pynq_tutorial.bit")

led_addr = ol.ip_dict["swsleds_gpio"]['phys_addr']

from pynq import MMIO
CH2_OFFSET = 0x8
leds = MMIO(led_addr + CH2_OFFSET)

leds.write(0, 1) # Turn on LD0

from pynq import overlay
from pynq import DefaultIP


In [4]:
import pynq.lib.dma

mmol = pynq.Overlay("/home/xilinx/jupyter_notebooks/pp4fpga/matrixm/matrixm.bit")

dma0 = mmol.axi_dma_0
dma1 = mmol.axi_dma_1


from pynq import Xlnk
xlnk = Xlnk()
A = xlnk.cma_array(shape=(32,32), dtype=np.int)
B = xlnk.cma_array(shape=(32,32), dtype=np.int)
AB = xlnk.cma_array(shape=(32,32), dtype=np.int)
test = xlnk.cma_array(shape=(32,32), dtype=np.int)

for i in range(32):
    for j in range(32):
        A[i][j] = 2;
        B[i][j] = 2;
               
dma0.sendchannel.transfer(A)
dma1.sendchannel.transfer(B)
dma0.recvchannel.transfer(AB)
dma1.recvchannel.transfer(test)

print(A)
print(B)
print(AB)

[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
[[128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
